# Generated by Django 3.2.7 on 2021-11-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_details',
            field=models.CharField(default='paaiskinimas', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_input',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
